src/main/java/com/homeadvisor/kafdrop/model/ClusterSummaryVO.java
/*
 * Copyright 2017 HomeAdvisor, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *
 */

package com.homeadvisor.kafdrop.model;

import kafka.cluster.Cluster;

import java.util.*;

public class ClusterSummaryVO {
    private int topicCount;
    private int partitionCount;
    private int underReplicatedCount;
    private double preferredReplicaPercent;

    /**
     * Number of partitions each broker is the leader for
     */
    private Map<Integer, Integer> brokerLeaderPartitionCount = new HashMap<>();

    /**
     * Number of partitions each broker should be the leader for
     */
    private Map<Integer, Integer> brokerPreferredLeaderPartitionCount = new HashMap<>();

    private Map<Integer, Integer> brokerUnderReplicationCount = new HashMap<>();

    private Set<Integer> expectedBrokerIds = new HashSet<>();

    public int getTopicCount() {
        return topicCount;
    }

    public void setTopicCount(int topicCount) {
        this.topicCount = topicCount;
    }

    public int getPartitionCount() {
        return partitionCount;
    }

    public void setPartitionCount(int partitionCount) {
        this.partitionCount = partitionCount;
    }

    public int getUnderReplicatedCount() {
        return underReplicatedCount;
    }

    public void setUnderReplicatedCount(int underReplicatedCount) {
        this.underReplicatedCount = underReplicatedCount;
    }

    public int getLaggingReplicaCount()
    {
        return getExpectedBrokerIds().stream()
           .mapToInt(this::getBrokerUnderReplicationCount)
           .sum();
    }

    public double getPreferredReplicaPercent() {
        return preferredReplicaPercent;
    }

    public void setPreferredReplicaPercent(double preferredReplicaPercent) {
        this.preferredReplicaPercent = preferredReplicaPercent;
    }

    public Map<Integer, Integer> getBrokerLeaderPartitionCount() {
        return brokerLeaderPartitionCount;
    }

    public Integer getBrokerLeaderPartitionCount(int brokerId) {
        return brokerLeaderPartitionCount.get(brokerId);
    }

    public void addBrokerLeaderPartition(int brokerId) {
        addBrokerLeaderPartition(brokerId, 1);
    }

    public void addBrokerLeaderPartition(int brokerId, int partitionCount) {
        brokerLeaderPartitionCount.compute(brokerId, (k, v) -> v == null ? partitionCount : v + partitionCount);
    }

    public Map<Integer, Integer> getBrokerPreferredLeaderPartitionCount() {
        return brokerPreferredLeaderPartitionCount;
    }

    public Integer getBrokerPreferredLeaderPartitionCount(int brokerId) {
        return brokerPreferredLeaderPartitionCount.get(brokerId);
    }

    public void addBrokerPreferredLeaderPartition(int brokerId) {
        addBrokerPreferredLeaderPartition(brokerId, 1);
    }

    public void addBrokerPreferredLeaderPartition(int brokerId, int partitionCount) {
        brokerPreferredLeaderPartitionCount.compute(brokerId, (k, v) -> v == null ? partitionCount : v + partitionCount);
    }

    public Collection<Integer> getExpectedBrokerIds() {
        return expectedBrokerIds;
    }

    public void addExpectedBrokerId(int brokerId)
    {
        expectedBrokerIds.add(brokerId);
    }

    public void addBrokerUnderReplicatedPartition(int brokerId)
    {
        addBrokerUnderReplicatedPartitions(brokerId, 1);
    }

    public void addBrokerUnderReplicatedPartitions(int brokerId, int underReplicatedCount)
    {
        brokerUnderReplicationCount.merge(brokerId, underReplicatedCount, Integer::sum);
    }

    public Map<Integer, Integer> getBrokerUnderReplicationCount()
    {
        return brokerUnderReplicationCount;
    }

    public Integer getBrokerUnderReplicationCount(int brokerId)
    {
        return brokerUnderReplicationCount.get(brokerId);
    }

    public ClusterSummaryVO merge(ClusterSummaryVO that)
    {
        this.setPartitionCount(this.getPartitionCount() + that.getPartitionCount());
        this.setUnderReplicatedCount(this.getUnderReplicatedCount() + that.getUnderReplicatedCount());
        this.setPreferredReplicaPercent(this.getPreferredReplicaPercent() + that.getPreferredReplicaPercent());
        that.getBrokerLeaderPartitionCount().forEach(this::addBrokerLeaderPartition);
        that.getBrokerPreferredLeaderPartitionCount().forEach(this::addBrokerPreferredLeaderPartition);
        that.getBrokerUnderReplicationCount().forEach(this::addBrokerUnderReplicatedPartitions);
        that.getExpectedBrokerIds().forEach(this::addExpectedBrokerId);

        return this;
    }
}

src/main/java/com/homeadvisor/kafdrop/model/ConsumerTopicVO.java
/*
 * Copyright 2017 HomeAdvisor, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *
 */

package com.homeadvisor.kafdrop.model;

import java.util.*;

public class ConsumerTopicVO
{
   private final String topic;
   private final String groupId;
   private final Map<Integer, ConsumerPartitionVO> offsets = new TreeMap<>();

   public ConsumerTopicVO(String topic, String groupId)
   {
      this.topic = topic;
      this.groupId = groupId;
   }

   public String getTopic()
   {
      return topic;
   }

   public void addOffset(ConsumerPartitionVO offset)
   {
      offsets.put(offset.getPartitionId(), offset);
   }

   public long getLag()
   {
      return offsets.values().stream()
         .map(ConsumerPartitionVO::getLag)
         .filter(lag -> lag >= 0)
         .reduce(0L, Long::sum);
   }

   public long getMaxLag()
   {
      return offsets.values().stream()
         .map(ConsumerPartitionVO::getLag)
         .filter(lag -> lag >= 0)
         .reduce(0L, Long::max);
   }

   public Collection<ConsumerPartitionVO> getPartitions()
   {
      return offsets.values();
   }

   public ConsumerPartitionVO getPartition(int partitionId)
   {
      return offsets.get(partitionId);
   }

   public ConsumerPartitionVO getOrCreatePartition(int partitionId)
   {
      return offsets.computeIfAbsent(partitionId, id -> new ConsumerPartitionVO(groupId, topic, id));
   }

   public double getCoveragePercent()
   {
      return (offsets.size() > 0) ? ((double)getAssignedPartitionCount()) / offsets.size() : 0.0;
   }

   public int getAssignedPartitionCount()
   {
      return (int) offsets.values().stream()
         .filter(p -> p.getOwner() != null)
         .count();
   }

   public int getOwnerCount()
   {
      return (int)offsets.values().stream()
         .map(ConsumerPartitionVO::getOwner)
         .filter(Objects::nonNull)
         .distinct()
         .count();
   }
}

src/main/java/com/homeadvisor/kafdrop/model/ConsumerVO.java
/*
 * Copyright 2017 HomeAdvisor, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *
 */

package com.homeadvisor.kafdrop.model;

import org.apache.commons.lang.Validate;

import java.util.*;
import java.util.stream.Collectors;

public class ConsumerVO implements Comparable<ConsumerVO>
{
   private String groupId;
   private Map<String, ConsumerTopicVO> topics = new TreeMap<>();
   private List<ConsumerRegistrationVO> activeInstances = new ArrayList<>();
   private boolean legacy = false;

   public ConsumerVO(String groupId)
   {
      Validate.notEmpty("groupId is required");
      this.groupId = groupId;
   }

   public boolean isLegacy()
   {
      return legacy;
   }

   public void setLegacy(boolean legacy)
   {
      this.legacy = legacy;
   }

   public String getGroupId()
   {
      return groupId;
   }

   public void setGroupId(String groupId)
   {
      this.groupId = groupId;
   }

   public void addActiveInstance(ConsumerRegistrationVO id)
   {
      activeInstances.add(id);
   }

   public List<ConsumerRegistrationVO> getActiveInstances()
   {
      return activeInstances;
   }

   public List<ConsumerRegistrationVO> getActiveInstancesForTopic(String topic)
   {
      return activeInstances.stream()
         .filter(registration -> registration.subscribesToTopic(topic))
         .collect(Collectors.toList());
   }

   public void addTopic(ConsumerTopicVO topic)
   {
      topics.put(topic.getTopic(), topic);
   }

   public ConsumerTopicVO getTopic(String topic)
   {
      return topics.get(topic);
   }

   public ConsumerTopicVO getOrCreateTopic(String topic)
   {
      ConsumerTopicVO consumerTopic = getTopic(topic);
      if (consumerTopic == null)
      {
         consumerTopic = new ConsumerTopicVO(topic, groupId);
         addTopic(consumerTopic);
      }
      return consumerTopic;
   }

   public Collection<ConsumerTopicVO> getTopics()
   {
      return topics.values();
   }

   public int getActiveTopicCount()
   {
      return topics.values().stream()
         .map(t -> t.getAssignedPartitionCount() > 0 ? 1 : 0)
         .reduce(0, Integer::sum);
   }

   @Override
   public int compareTo(ConsumerVO that)
   {
      return this.groupId.compareTo(that.groupId);
   }

   @Override
   public boolean equals(Object o)
   {
      if (this == o) return true;
      if (o == null || getClass() != o.getClass()) return false;

      ConsumerVO vo = (ConsumerVO) o;

      if (!groupId.equals(vo.groupId)) return false;

      return true;
   }

   @Override
   public int hashCode()
   {
      return groupId.hashCode();
   }

}

src/main/java/com/homeadvisor/kafdrop/model/TopicVO.java
/*
 * Copyright 2017 HomeAdvisor, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *
 */

package com.homeadvisor.kafdrop.model;

import java.util.*;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class TopicVO implements Comparable<TopicVO>
{
   private String name;
   private Map<Integer, TopicPartitionVO> partitions = new TreeMap<>();
   private Map<String, Object> config = new TreeMap<>();
   // description?
   // partition state
   // delete supported?


   public TopicVO(String name)
   {
      this.name = name;
   }

   public String getName()
   {
      return name;
   }

   public void setName(String name)
   {
      this.name = name;
   }

   public Map<String, Object> getConfig()
   {
      return config;
   }

   public void setConfig(Map<String, Object> config)
   {
      this.config = config;
   }

   public Collection<TopicPartitionVO> getPartitions()
   {
      return partitions.values();
   }

   public Optional<TopicPartitionVO> getPartition(int partitionId)
   {
      return Optional.ofNullable(partitions.get(partitionId));
   }

   public Map<Integer, TopicPartitionVO> getPartitionMap() {
     return Collections.unmodifiableMap(partitions);
   }

   public Collection<TopicPartitionVO> getLeaderPartitions(int brokerId)
   {
      return partitions.values().stream()
         .filter(tp -> tp.getLeader() != null && tp.getLeader().getId() == brokerId)
         .collect(Collectors.toList());
   }

   public Collection<TopicPartitionVO> getUnderReplicatedPartitions()
   {
      return getUnderReplicatedPartitionStream()
         .collect(Collectors.toList());
   }

   private Stream<TopicPartitionVO> getUnderReplicatedPartitionStream()
   {
      return partitions.values().stream()
         .filter(TopicPartitionVO::isUnderReplicated);
   }

   /**
    * Returns the brokers that have under-replicated partition data
    * @return Set of broker ids
    */
   public Set<Integer> getUnderreplicatedBrokerIds()
   {
      return getUnderReplicatedPartitionStream()
         .flatMap(TopicPartitionVO::getOutOfSyncReplicaStream)
         .collect(Collectors.toSet());
   }

   public void setPartitions(Map<Integer, TopicPartitionVO> partitions)
   {
      this.partitions = partitions;
   }

   /**
    * Returns the total number of messages published to the topic, ever
    * @return
    */
   public long getTotalSize()
   {
      return partitions.values().stream()
         .map(TopicPartitionVO::getSize)
         .reduce(0L, Long::sum);
   }

   /**
    * Returns the total number of messages available to consume from the topic.
    * @return
    */
   public long getAvailableSize()
   {
      return partitions.values().stream()
         .map(p -> p.getSize() - p.getFirstOffset())
         .reduce(0L, Long::sum);
   }

   public double getPreferredReplicaPercent()
   {
      long preferredLeaderCount = partitions.values().stream()
         .filter(TopicPartitionVO::isLeaderPreferred)
         .count();
      return ((double) preferredLeaderCount) / ((double)partitions.size());
   }

   public Map<String, List<TopicPartitionVO.PartitionReplica>> getBrokerLeaders()
   {
      return partitions.values().stream()
              .map(TopicPartitionVO::getLeader)
              .filter(Objects::nonNull)
              .collect(Collectors.groupingBy(leader -> leader.getId().toString(), TreeMap::new, Collectors.toList()));
   }

   public Map<Integer, BrokerReplicas> getBrokerReplicas()
   {
      Map<Integer, BrokerReplicas> brokerReplicasMap = new TreeMap<>();
      partitions.values().stream()
         .flatMap(tp -> tp.getReplicas().stream())
         .forEach(r -> brokerReplicasMap.computeIfAbsent(r.getId(), id -> new BrokerReplicas(id.toString()))
            .addReplica(r));
      return brokerReplicasMap;
   }

   public static class BrokerReplicas
   {
      /** The ID of the broker owning the replicas */
      private final String brokerId;
      /** List of leader replicas on this broker */
      private final List<TopicPartitionVO.PartitionReplica> leaders = new ArrayList<>();
      /** List of non-leader replicas on this broker */
      private final List<TopicPartitionVO.PartitionReplica> replicas = new ArrayList<>();

      public BrokerReplicas(String brokerId) {
         this.brokerId = brokerId;
      }

      public void addReplica(TopicPartitionVO.PartitionReplica replica)
      {
         if (replica.isLeader()) {
            leaders.add(replica);
         }
         else {
            replicas.add(replica);
         }
      }

      public String getBrokerId()
      {
         return brokerId;
      }

      public List<TopicPartitionVO.PartitionReplica> getLeaders()
      {
         return leaders;
      }

      public List<TopicPartitionVO.PartitionReplica> getReplicas()
      {
         return replicas;
      }
   }

   public void addPartition(TopicPartitionVO partition)
   {
      partitions.put(partition.getId(), partition);
   }

   @Override
   public int compareTo(TopicVO that)
   {
      return this.name.compareTo(that.name);
   }

   @Override
   public boolean equals(Object o)
   {
      if (this == o) return true;
      if (o == null || getClass() != o.getClass()) return false;

      TopicVO that = (TopicVO) o;

      if (!name.equals(that.name)) return false;

      return true;
   }

   @Override
   public int hashCode()
   {
      return name.hashCode();
   }

}

src/main/resources/templates/broker-detail.ftl
<#--
 Copyright 2016 HomeAdvisor, Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->
<#import "lib/template.ftl" as template>
<@template.header "Broker: ${broker.id?string}">
<style type="text/css">
    .bs-table.overview td { white-space: nowrap; }

    td.leader-partitions { word-break: break-all; }

</style>
</@template.header>

<#setting number_format="0">

<h1>Broker Id: ${broker.id}</h1>

<div id="topic-overview">
    <h2>Broker Overview</h2>

    <table class="table table-bordered overview">
        <tbody>
        <tr>
            <td><i class="fa fa-laptop"></i> Host</td>
            <td>${broker.host}:${broker.port}</td>
        </tr>
        <tr>
            <td><i class="fa fa-clock-o"></i> Start Time</td>
            <td>${broker.timestamp?string["yyyy-MM-dd HH:mm:ss.SSSZ"]}</td>
        </tr>
        <tr>
            <td>Controller</td>
            <td><@template.yn broker.controller/></td>
        </tr>
        <tr>
            <td># of Topics</td>
            <td>${topics?size}</td>
        </tr>

        <#assign partitionCount=0>
        <#list topics as t>
            <#assign partitionCount=partitionCount+(t.getLeaderPartitions(broker.id)?size)>
        </#list>
        <tr>
            <td># of Partitions</td>
            <td>${partitionCount}</td>
        </tr>
        </tbody>
    </table>
</div>

<div>
    <h2>Topic Detail</h2>

    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Topic</th>
            <th>Total Partitions</th>
            <th>Broker Partitions</th>
            <th>Partition Ids</th>
        </tr>
        </thead>
        <tbody>
        <#list topics as t>
              <tr>
                  <td><a href="/topic/${t.name}">${t.name}</a></td>
                  <td>${t.partitions?size}</td>
                  <td>${t.getLeaderPartitions(broker.id)?size}</td>
                  <td class="leader-partitions"><#list t.getLeaderPartitions(broker.id) as p>${p.id}<#sep>,</#list></td>
              </tr>
        </#list>
        </tbody>
    </table>
</div>

<#if brokerConfig??>
<div>
    <h2>Configuration</h2>

    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Name</th>
            <th>Value</th>
            <th>Source</th>
        </tr>
        </thead>
        <tbody>
        <#list brokerConfig.entries as e>
              <tr>
                  <td>${e.name}</td>
                  <td><#if e.sensitive>xxxxxxxxxx (hidden)<#else>${e.value!''}</#if>
                  </td>
                  <td>${e.source}</td>
              </tr>
        </#list>
        </tbody>
    </table>
</div>
</#if>

<@template.footer/>

src/main/resources/templates/consumer-detail.ftl
<#--
 Copyright 2016 HomeAdvisor, Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->
<#import "lib/template.ftl" as template>
<@template.header "Consumer: ${consumer.groupId}"/>

<#setting number_format="0">

<h1>Kafka Consumer: ${consumer.groupId} <#if consumer.legacy>(legacy)</#if></h1>

<div id="overview">
    <h2>Overview</h2>
    <table class="table table-bordered overview">
        <tbody>
        <tr>
            <td>Active Instances</td>
            <td>${consumer.activeInstances?size}</td>
        </tr>
        <tr>
            <td>Topics</td>
            <td>${consumer.topics?size}</td>
        </tr>
        <tr>
            <td>Active Topics</td>
            <td>${consumer.activeTopicCount}</td>
        </tr>
        </tbody>
    </table>
</div>

<div id="topics">
<#list consumer.topics as consumerTopic>
    <#assign tableId='topic-${consumerTopic_index}-table'>
    <h2><@template.toggleLink target="#${tableId}" anchor='${tableId}' /> Topic: <a href="/consumer/${consumer.groupId}/${consumerTopic.topic}">${consumerTopic.topic}</a></h2>
    <div id="${tableId}">
        <p>
            <table class="table table-bordered overview">
                <tbody>
                    <tr>
                        <td>Total Threads</td>
                        <td>${consumerTopic.ownerCount}</td>
                    </tr>
                    <tr>
                        <td>Partition Coverage</td>
                        <td>${consumerTopic.coveragePercent * 100.0}%
                            (${consumerTopic.assignedPartitionCount} of ${consumerTopic.partitions?size})</td>
                    </tr>
                    <tr>
                        <td>Max Lag</td>
                        <td>${consumerTopic.maxLag}</td>
                    </tr>
                </tbody>
            </table>
        </p>
        <p>
            <table class="table table-bordered table-condensed">
                <thead>
                <tr>
                    <th>Partition</th>
                    <th>First Offset</th>
                    <th>Last Offset</th>
                    <#if consumer.legacy>
                       <th>Kafka Offset</th>
                       <th>Kafka Lag</th>
                       <th>Zookeeper Offset</th>
                       <th>Zookeeper Lag</th>
                    <#else>
                        <th>Current Offset</th>
                        <th>Lag</th>
                    </#if>
                    <th>Owner</th>
                </tr>
                </thead>
                <tbody>
                <#list consumerTopic.partitions as p>
                   <tr>
                       <td>${p.partitionId}</td>
                       <td>${p.firstOffset}</td>
                       <td>${p.size}</td>
                       <td>${p.consumerOffset.kafkaOffset}</td>
                       <td>${p.kafkaLag}</td>
                       <#if consumer.legacy>
                         <td>${p.consumerOffset.zookeeperOffset}</td>
                         <td>${p.zookeeperLag}</td>
                       </#if>
                       <td>${p.owner!''}</td>
                   </tr>
                </#list>
                </tbody>
            </table>
        </p>
    </div>
</#list>

</div>

<@template.footer/>

src/main/resources/templates/not-initialized.ftl
<#--
 Copyright 2016 HomeAdvisor, Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->
<#import "lib/template.ftl" as template>
<@template.header "Initializing...">
   <meta http-equiv="refresh" content="5" >
</@template.header>

<div>
    <p>Internal caches are still initializing. Please wait...</p>
</div>

<@template.footer/>

src/main/resources/templates/topic-detail.ftl
<#--
 Copyright 2016 HomeAdvisor, Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->
<#import "lib/template.ftl" as template>
<@template.header "Topic: ${topic.name}">
  <style type="text/css">
      #action-bar { margin-top: 17px; }
      th { word-break: break-all; }
  </style>
</@template.header>

<#setting number_format="0">

<h1>Topic: ${topic.name}</h1>

<div id="action-bar" class="container">
    <a class="btn btn-default" href="/topic/${topic.name}/messages"><i class="fa fa-eye"></i> View Messages</a>
</div>

<div class="container-fluid">
<div class="row">

<div id="topic-overview" class="col-md-5">
    <h2>Overview</h2>

    <table class="table table-bordered">
        <tbody>
        <tr>
            <td># of Partitions</td>
            <td>${topic.partitions?size}</td>
        </tr>
        <tr>
            <td>Preferred Replicas</td>
            <td <#if topic.preferredReplicaPercent lt 1.0>class="warning"</#if>>${topic.preferredReplicaPercent?string.percent}</td>
        </tr>
        <tr>
            <td>Under Replicated Partitions</td>
            <td <#if topic.underReplicatedPartitions?size gt 0>class="warning"</#if>>${topic.underReplicatedPartitions?size}</td>
        </tr>
        <tr>
            <td>Total Size</td>
            <td>${topic.totalSize}</td>
        </tr>
        <tr>
            <td>Total Available Messages</td>
            <td>${topic.availableSize}</td>
        </tr>
        </tbody>
    </table>
</div>


<div id="topic-config" class="col-md-7">
    <h2>Configuration</h2>

    <#if topic.config?size == 0>
    <div>No topic specific configuration</div>
    <#else>
    <table class="table table-bordered">
        <tbody>
        <#list topic.config?keys as c>
              <tr>
                  <td>${c}</td>
                  <td>${topic.config[c]}</td>
              </tr>
        </#list>
        </tbody>
    </table>
    </#if>
</div>

</div>

<div class="row">
<div id="partition-detail" class="col-md-5">
    <h2>Partition Detail</h2>
    <table id="partition-detail-table" class="table table-bordered table-condensed small">
        <thead>
        <tr>
            <th>Partition</th>
            <th>First Offset</th>
            <th>Last Offset</th>
            <th>Size</th>
            <th>Leader</th>
            <th>Replicas</th>
            <th>In Sync Replicas</th>
            <th>Preferred Leader?</th>
            <th>Under Replicated?</th>
        </tr>
        </thead>
        <tbody>
        <#list topic.partitions as p>
        <tr>
            <td>${p.id}</td>
            <td>${p.firstOffset}</td>
            <td>${p.size}</td>
            <td>${p.size - p.firstOffset}</td>
            <td <#if !(p.leader)??>class="warning"</#if>>${(p.leader.id)!"none"}</td>
            <td><#list p.replicas as r>${r.id}<#if r_has_next>,</#if></#list></td>
            <td><#list p.inSyncReplicas as r>${r.id}<#if r_has_next>,</#if></#list></td>
            <td <#if !p.leaderPreferred>class="warning"</#if>><@template.yn p.leaderPreferred/></td>
            <td <#if p.underReplicated>class="warning"</#if>><@template.yn p.underReplicated/></td>
        </tr>
        </#list>
        </tbody>
    </table>
</div>

<div id="consumers" class="col-md-7">
    <h2>Consumers</h2>
    <table id="consumers-table" class="table table-bordered table-condensed small">
        <thead>
        <tr>
            <th>Group Id</th>
            <th>Lag</th>
            <th>Active Instances</th>
        </tr>
        </thead>
        <tbody>
        <#list consumers![] as c>
            <tr>
                <#if c.legacy>
                <td><a href="/legacy/consumer/${c.groupId}">${c.groupId}</a> (legacy)</td>
                <#else>
                <td><a href="/consumer/${c.groupId}">${c.groupId}</a></td>
                </#if>
                <td>${c.getTopic(topic.name).lag}</td>
                <td>
                    <ul class="list-unstyled">
                   <#list c.getActiveInstancesForTopic(topic.name) as i>
                       <li>${i.id}</li>
                   </#list>
                    </ul>
                </td>
            </tr>
        </#list>
        </tbody>
    </table>
</div>
</div>
</div>
<@template.footer/>